version: "3.1"

networks:
  net:

volumes:
  mongodb_data:

services:
  server:
    build: .
    container_name: server
    ports:
      - "8080:8080"
    networks:
      - net
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB_NAME=medialab
      - MONGODB_COL_NAME=viz
      - ROOT_ASSETS_FOLDER=/www/assets
    volumes:
      - $PWD:/www

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    command: --quiet
    ports:
      - "27017:27017"
    networks:
      - net
    environment:
      - MONGO_INITDB_DATABASE=medialab
      - MONGO_COLLECTION_NAME=viz
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongodb_data:/data/db
