version: "3.1"

networks:
  net:

volumes:
  mongodb_data:

services:
  server:
    build: .
    ports:
      - "8080:8080"
    networks:
      - net
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/

  mongodb:
    image: mongo:4.4
    command: --quiet
    ports:
      - "27017:27017"
    networks:
      - net
    environment:
      - MONGO_INITDB_DATABASE=notebook
    volumes:
      - mongodb_data:/data/db
